#!/bin/bash
source /opt/stateless/engine/includes/phvalheim-static.conf

# update database with last run time for this script. We update the timestamp before and after the script in the event the script exits.
/opt/stateless/engine/tools/sql "UPDATE systemstats SET utilizationMonitorLastRun=NOW();"

echo "`date` [NOTICE : phvalheim] Polling System Stats..."


#### BEGIN: global ####
currentCpuUtilization=$(echo "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]")
SQL "UPDATE systemstats SET currentCpuUtilization='$currentCpuUtilization'"
#### END: global ####


#### BEGIN: worlds ####

allWorlds=$(SQL "SELECT name FROM worlds")

for world in $allWorlds; do
	thisWorldState=$(/usr/bin/supervisorctl status|grep -w valheimworld_$world|tr -s " "|cut -d " " -f2)

		if [ "$thisWorldState" = "RUNNING" ]; then
			thisWorldPID=$(supervisorctl status|grep -w valheimworld_$world|tr -s " "|cut -d " " -f4|cut -d "," -f1)
			thisWorldState="online"
			thisWorldMemory=$(ps -p $thisWorldPID -o rss=)
			thisWorldMemoryFriendly="${thisWorldMemory}bytes"

			#convert to MB
			if [ $thisWorldMemory -gt 1024 ]; then
				thisWorldMemory=$(echo "$thisWorldMemory/1024"|bc)
				thisWorldMemoryFriendly="${thisWorldMemory}MB"

				#convert to GB
				if [ $thisWorldMemory -gt 1024 ]; then
					thisWorldMemory=$(echo "scale=2;$thisWorldMemory/1024"|bc)
					thisWorldMemoryFriendly="${thisWorldMemory}GB"
				fi

			fi

		else
			thisWorldPID="offline"
			thisWorldState="offline"
			thisWorldMemoryFriendly="offline"
		fi
	#echo
	#echo "World Name: $world"
	#echo "World State: $thisWorldState"
	#echo "World PID: $thisWorldPID"
	#echo "World Memory: $thisWorldMemoryFriendly"
	
	#Update database with latest data
	SQL "UPDATE worlds SET currentMemory='$thisWorldMemoryFriendly' WHERE name='$world'"
done

#### END: worlds ####


# update database with last run time for this script. We update the timestamp before and after the script in the event the script exits.
/opt/stateless/engine/tools/sql "UPDATE systemstats SET utilizationMonitorLastRun=NOW();"
