#!/bin/bash
source /opt/stateless/engine/includes/phvalheim-static.conf
#source /opt/stateful/config/phvalheim-backend.conf

# update database
/opt/stateless/engine/tools/sql "UPDATE systemstats SET worldBackupLastExecStatus='running';"


# error setter
function errorSetter() {
        RESULT=$1

        if [ $RESULT -ne 0 ]; then
                /opt/stateless/engine/tools/sql "UPDATE systemstats SET worldBackupLastExecStatus='error';"
                exit 1
        fi
}


#$1=worldName, $2=backupsToKeep
function purgeOldBackups() {
        worldName="$1"
        backupsToKeep="$2"

        backupFiles=$(ls -alt $backupDir/valheimworld_$worldName-***.tar|rev|cut -d " " -f1|rev)
        totalBackups=$(echo "$backupFiles"|wc -l)
        keepBackups=$(echo "$backupFiles"|head -$backupsToKeep)

        if [ $totalBackups -gt $backupsToKeep ]; then
                numberOfBackupsToDelete=$(echo $totalBackups-$backupsToKeep|bc)
                deleteBackups=$(echo "$backupFiles"|tail -$numberOfBackupsToDelete)

                for deleteBackup in $deleteBackups; do
                        echo "`date` [phvalheim] Deleting old backup $deleteBackup..."
                        rm -f "$deleteBackup"
			errorSetter $?
                done
        fi
}


#$1=worldName
function backupWorld(){
        worldName="$1"

	backupTimeStamp=''
	backupDestinationFile=''
	backupTimeTaken=''
	backupSize=''


        cd $worldsDirectoryRoot/$worldName/game/.config/unity3d/IronGate/Valheim/
	if [ ! $? = 0 ]; then
		echo "`date` [WARN : phvalheim] .config directory missing for '$worldName', skipping backup..."
	else
	        backupTimeStamp=$(date +%Y-%m-%dT%H:%M:%S%z)
		errorSetter $?

	        backupDestinationFile="$backupDir/valheimworld_$worldName-$backupTimeStamp.tar"

	        backupTimeTaken=$(/usr/bin/time --format='%e' /usr/bin/tar cf $backupDestinationFile . 2>&1)
		errorSetter $?

	        backupSize=$(stat --format=%s "$backupDestinationFile")
		errorSetter $?

		#echo
		echo "`date` [phvalheim]  Backup time (seconds): $backupTimeTaken"
		#echo
		echo "`date` [phvalheim]  Backup size (bytes): $backupSize"
	fi
}


#echo
echo "`date` [NOTICE : phvalheim] Starting world backups..."
#echo
echo "`date` [phvalheim]  Backup directory: $backupDir"
#echo


#backup all the worlds
worldNames=$(SQL "SELECT name FROM worlds;")
for worldName in $worldNames; do

        echo "`date` [phvalheim]  World backup started for '$worldName'..."

        #run backup
        backupWorld "$worldName"
	errorSetter $?

        if [ -f "$backupDestinationFile" ]; then
                echo "`date` [NOTICE : phvalheim]  Backup written to: $backupDestinationFile"
                purgeOldBackups $worldName $backupsToKeep
		errorSetter $?
                continue
        else
                echo "`date` [FAIL : phvalheim]  Backup failed for '$worldName'!"
		errorSetter $?
                continue
        fi

done

# update database
/opt/stateless/engine/tools/sql "UPDATE systemstats SET worldBackupLastExecStatus='idle';"
/opt/stateless/engine/tools/sql "UPDATE systemstats SET worldBackupLastRun=NOW();"
